name: Go

on:
  push:
    branchers: [master]
  pull_request:
    branches: [master]

jobs:

  Lint:
    name: GoLinty
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Go-Linty
        uses: ArangoGutierrez/GoLinty-Action@go-1.13rc1-alpine
        env:
          GO111MODULE: on
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build App
        run: go build simulator.go

  Artefato:
    name: Artefato
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - run: mkdir -p artefato

      - run: echo hello > artefato/world.txt

      - uses: actions/upload-artifact@v1
        with:
          name: meu-artefato
          path: artefato