name: Go

on:
  push:
    branchers: [master]
  pull_request:
    branches: [master]

jobs:

  Lint:
    name: GoLinty
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Go-Linty
        uses: ArangoGutierrez/GoLinty-Action@go-1.13rc1-alpine
        env:
          GO111MODULE: on
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build App
        run: go build simulator.go

  Artefato:
    name: Artefato
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go

      - name: Checkout
        uses: actions/checkout@v2

      - name: Criar pasta
        run: mkdir -p artefato

      - name: Criar executável
        run: GOOS=windows go build simulator.go

      - name: Sleep for 10 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '10s'

      - name: Mover para pasta artefato
        run: sudo mv simulator.exe /artefato

      - name: Sleep for 10 seconds
        uses: jakejarvis/wait-action@master
        with:
          time: '10s'

      - name: Criar artefato
        uses: actions/upload-artifact@v1
        with:
          name: simulador
          path: artefato