name: Go

on:
  push:
    branchers: [master]
  pull_request:
    branches: [master]

jobs:

  Lint:
    name: GoLinty
    runs-on: ubuntu-latest
    steps:

      - name: Check out code into the Go module directory
        uses: actions/checkout@v1
      - name: Go-Linty
        uses: ArangoGutierrez/GoLinty-Action@go-1.13rc1-alpine
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  Build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Setup Go
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go

      - name: Checkout
        uses: actions/checkout@v2

      - name: Build App
        run: go build driver.go

  Release-linux-amd64:
    name: release linux/amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: compile and release
        uses: ngs/go-release.action@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GOARCH: amd64
          GOOS: linux